language: node_js

sudo: true

services:
  - docker

node_js:
  - "8.9.0"

env:
  global:
    - NVM_DIR="${TRAVIS_BUILD_DIR}"
    - RUNNING_IN_TRAVIS=true

install:
  -

cache:
  directories:
    - node_modules
    - public/bower_components

before_script:
  - sudo service mysql stop
  - docker stop $(docker ps -a -q) || true
  - docker rm -f $(docker ps -a -q) || true
  - docker rmi -f $(docker ps -a -q) || true
  - ${TRAVIS_BUILD_DIR}/conf/scripts/docker/nuke_and_rebuild.sh

script:
  - nvm use 8.9.0
  - npm run calculate-coverage

after_success:
  - nvm use 8.9.0
  - npm run report-coverage


after_script:
  - docker stop $(docker ps -a -q) || true
  - docker rm -f $(docker ps -a -q) || true
  - docker rmi -f $(docker ps -a -q) || true
