language: node_js

sudo: true

services:
  - docker

node_js:
  - "8.10.0"

env:
  global:
    - NVM_DIR="${TRAVIS_BUILD_DIR}"
    - RUNNING_IN_TRAVIS=true

cache:
  directories:
    - node_modules
    - public/bower_components

install:
  - ${TRAVIS_BUILD_DIR}/conf/scripts/install.sh

script:
  - nvm use 8.10.0
  - npm run calculate-coverage

after_success:
  - nvm use 8.10.0
  - npm run report-coverage


after_script:
  - docker stop $(docker ps -a -q) || true
  - docker rm -f $(docker ps -a -q) || true
  - docker rmi -f $(docker ps -a -q) || true
