version: '3.2'

services:
  elasticsearch:
    container_name: elasticsearch-dendro
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - target: 9202
        published: 9200
      - target: 9302
        published: 9300
    environment:
      - "discovery.type=single-node"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "TAKE_FILE_OWNERSHIP=1"
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data:consistent
    networks:
      - dendro-docker
    restart: on-failure

  virtuoso:
    container_name: virtuoso-dendro
    image: joaorosilva/virtuoso:7.2.4-for-dendro-0.4
    ports:
      - target: 8890
        published: 8892
      - target: 1111
        published: 1113
    environment:
      - "SPARQL_UPDATE=true"
      - "VIRT_Parameters_CheckpointSyncMode=2"
      - "VIRT_Parameters_PageMapCheck=1"
      - "VIRT_Parameters_CheckpointInterval=0"
    networks:
      - dendro-docker
    restart: on-failure

  mariadb:
    container_name: mariadb-dendro
    image: mariadb:5.5.62
    ports:
      - target: 3306
        published: 3308
    environment:
      - "MYSQL_ROOT_PASSWORD=r00t_p4ssw0rd"
      - "MYSQL_DATABASE=dendro_data"
      - "MYSQL_USER=dendro"
      - "MYSQL_PASSWORD=dendr0_p4ssw0rd"
    volumes:
      - ./volumes/mariadb:/var/lib/mariadb
    networks:
      - dendro-docker
    restart: on-failure

  mongodb:
    container_name: mongodb-dendro
    image: mongo:3.6.0
    ports:
      - target: 27017
        published: 27019
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=34857q98efhlajwehrlaeroiu2yq3948q2uweoiqwherluqywioerqhw0p92874983724rhqwelrhqweiuryoiqwerhlqwhjeflkawejrp9023475823y4rjhelkjrheiouryi
    volumes:
      - ./volumes/mongo:/data/db
    networks:
      - dendro-docker
    command: mongod --smallfiles --bind_ip_all
    restart: on-failure

  dendro:
    container_name: dendro
    image: feupinfolab/dendro:dendrokeywords
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - target: 3001
        published: 3001
    depends_on:
      - elasticsearch
      - mariadb
      - mongodb
      - virtuoso
    volumes:
        - ./volumes/dendro:/dendro/dendro
    environment:
      DENDRO_ACTIVE_DEPLOYMENT_CONFIG: docker
    networks:
      - dendro-docker
    restart: always

networks:
  dendro-docker: {}
