version: '3'

services:
  jupyter_notebook:
    container_name: jupyter-dendro
    image:  jupyter/scipy-notebook:17aba6048f44
    environment:
      - VIRTUAL_HOST=${DENDRO_NOTEBOOK_VIRTUAL_HOST}
      # - VIRTUAL_PORT=${DENDRO_NOTEBOOK_VIRTUAL_HOST}
      #- JAVA_XMX=3g
    # ports:
    #  - 8888:8888
    expose:
      - 8888
