version: '3'

services:
  jupyter_notebook:
    container_name: ${DENDRO_NOTEBOOK_GUID}jupyter-dendro
    image:  jupyter/scipy-notebook:17aba6048f44
    environment:
      - VIRTUAL_HOST=${DENDRO_NOTEBOOK_VIRTUAL_HOST}
      - VIRTUAL_PORT=8888
      #- JAVA_XMX=3g
    volumes:
      - ./data:/home/jovyam/work
#
    networks:
      - traefikweb
    expose:
      - 8888

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"

networks:
  traefikweb:
    external:
      name: dendro_notebook_vhosts_traefikweb

#networks:
#      net:
#        name: notebooknet
#        driver: bridge
